// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/Jhooomn/file-transaction-processor/infrastructure/repository"
	mock "github.com/stretchr/testify/mock"
)

// ProcessorRepository is an autogenerated mock type for the ProcessorRepository type
type ProcessorRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: ctx, transactionsPerMonth, totalBalance, avgCredit, avgDebit, creditCount, debitCount, name, email
func (_m *ProcessorRepository) Save(ctx context.Context, transactionsPerMonth map[string]uint, totalBalance float64, avgCredit float64, avgDebit float64, creditCount uint, debitCount uint, name string, email string) error {
	ret := _m.Called(ctx, transactionsPerMonth, totalBalance, avgCredit, avgDebit, creditCount, debitCount, name, email)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]uint, float64, float64, float64, uint, uint, string, string) error); ok {
		r0 = rf(ctx, transactionsPerMonth, totalBalance, avgCredit, avgDebit, creditCount, debitCount, name, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// findByNameAndEmail provides a mock function with given fields: ctx, name, email
func (_m *ProcessorRepository) findByNameAndEmail(ctx context.Context, name string, email string) (*repository.TransactionSummary, error) {
	ret := _m.Called(ctx, name, email)

	if len(ret) == 0 {
		panic("no return value specified for findByNameAndEmail")
	}

	var r0 *repository.TransactionSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*repository.TransactionSummary, error)); ok {
		return rf(ctx, name, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *repository.TransactionSummary); ok {
		r0 = rf(ctx, name, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.TransactionSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, name, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProcessorRepository creates a new instance of ProcessorRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessorRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessorRepository {
	mock := &ProcessorRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
