// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProcessorServiceClient is an autogenerated mock type for the ProcessorServiceClient type
type ProcessorServiceClient struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *ProcessorServiceClient) Execute() {
	_m.Called()
}

// NewProcessorServiceClient creates a new instance of ProcessorServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessorServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProcessorServiceClient {
	mock := &ProcessorServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
